### ISSUE TITLE
SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by dineshmaths1** [voiceittech/voiceit2-nodejs#1]
I am using  node v8.11.1  version
1. npm install --save voiceit2-nodejs installed
2. let voiceit2 = require('voiceit2-nodejs'); 
Am getting this error
saavha_node/node_modules/voiceit2-nodejs/index.js:48
    this.getGroupsForUser = (options.callback) =>{
                                    ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/balaji/saavha_node/server.js:10:16)

**Comment by armaanbindra** [comment]
Hi @dineshmaths1,
Thank you for finding the issue and providing a fix for the Node wrapper! 👍 . We have fixed this and republished a newer version to github and NPM.
